### ISSUE TITLE
Android binding integration throw errors

### ISSUE THREAD

**Issue by icalderond** [VisualService/Xamarin.ZoomSDKBinding#13]
I follow the steps for Installation and integration using the android binding projects referenced. When a tried to compile it show this errors showed in the image below.

Example to reproduce
[https://github.com/icalderond/Xamarin.ZoomSDKBinding/tree/feature/sample-projects](https://github.com/icalderond/Xamarin.ZoomSDKBinding/tree/feature/sample-projects)

**Steps**
1.- Clone repository
2.- Rebuild project to show files of languaje to modify
3.- Run tool project to clean files with format error
4.- Build project

**Current result**
Appear error mentioned in this thread

**Expected result**
Have build correctly

![image](https://user-images.githubusercontent.com/5691112/193981394-8e7ba109-528b-4173-a78d-6ff1144caacf.png)

**Comment by icalderond** [comment]
@mdima @AdamDiament do you have a correct implementation using custom ui or default ui for Android?

**Comment by AdamDiament** [comment]
Replicated, working on a fix. It's caused by an issue with the upgrade to the latest android version (zoom added new dependencies) that I missed in the recent merge.

**Comment by AdamDiament** [comment]
@icalderond for a workaround use this nuget version. In the meantime I will try to fix the issues with the latest versiona dn create a working sample app.

**Comment by mdima** [comment]
Yes, also I found some cross dependencies that were somehow incompatible on the latest version. 
I compiled the nuget package and everything worked.

**Comment by AdamDiament** [comment]
@mdima I am using the nuget package generated using 5.11.10.8019 and it works fine for me too, using custom UI. Are you using default UI in your Android solution or custom?

**Comment by icalderond** [comment]
@mdima @AdamDiament 
I added the nugget library and i have the same errrors for Android.
I share a screenshoot when i followed the steps mentioned in README.
- I added the version mentioned 5.11.10.8019
- I added the file missing mentioned in README exo_values_polyfill.xml and exo_layout_polyfill.xml
- I run app in physical device and it throw the same errors 

Please let me know if you need that i upload my code on somewhere to test this case. But i think is simple repliacate this escenario.

![image](https://user-images.githubusercontent.com/5691112/194075185-cdfa3408-1af4-4268-a654-d366507dedfa.png)

**Comment by AdamDiament** [comment]
Thanks @icalderond - I think if you use the latest Nuget with default UI you will get these issues - I warned about these in the readme.

It is complicated to solve as it requires finding a way to upgrade to dependencies that Xamarin Forms does not support (and probably never will now Maui is here). So I don't see me having the time to fix this anytime soon. I suggest you try using the previous nuget version as per my previous comment, and check if default UI works with that (as mentioned, not guaranteed). 

Or you could look to implement a custom UI solution, which is what I have done in my project.

Thanks again.

**Comment by icalderond** [comment]
zoomsdksampleapp is reference of shared library in xamarin forms project

**Comment by AdamDiament** [comment]
> zoomsdksampleapp is reference of shared library in xamarin forms project

I know. I'm saying if you have both that and the nuget, you will get conflicts. They are essentially two versions of the same thing.

**Comment by icalderond** [comment]
> > zoomsdksampleapp is reference of shared library in xamarin forms project
> 
> I know. I'm saying if you have both that and the nuget, you will get conflicts. They are essentially two versions of the same thing.

@AdamDiament 

Please could you check the sample project that i have in my repo from Forked repo.
[https://github.com/icalderond/Xamarin.ZoomSDKBinding/tree/feature/sample-projects](https://github.com/icalderond/Xamarin.ZoomSDKBinding/tree/feature/sample-projects)

**Steps**
1.- Clone repository
2.- Rebuild project to show files of languaje to modify
3.- Run tool project to clean files with format error
4.- Build project

**Current result**
Appear error mentioned in this thread

**Expected result**
It have build correctly

**Comment by umeshkamble** [comment]
> @icalderond for a workaround use [this nuget version](https://www.nuget.org/packages/VisualService.Xamarin.Android.ZoomSDK/5.11.3.7251) and follow the steps in the readme. In the meantime I will try to fix the issues with the latest version and create a working sample app.

@AdamDiament  Any update?
