### ISSUE TITLE
Any idea when ios will be released & is it even partiall working?

### ISSUE THREAD

**Issue by AmrYousef** [VisualService/Xamarin.ZoomSDKBinding#5]
Hi, thank you so much for all the efforts you are making. I'm facing a big problem with zoom SDK due to the last stop to the old SDK zoom did. I wanted to ask if the current ios code you have is even partially working? and if you have any idea when you will release the ios binding?

thanks

**Comment by mdima** [comment]
Hello, I am working on it... I cannot give an ETA, but I don't feel so far...

**Comment by mdima** [comment]
@AmrYousef I committed everything for iOS and it is working. 
You can wait for @AdamDiament to accept the pull request and publish the nuget package or you can download and compile thi fork: https://github.com/mdima/Xamarin.ZoomSDKBinding

**Comment by AmrYousef** [comment]
Super Awesome, Thank you soooooooo much

**Comment by AmrYousef** [comment]
Hi @AdamDiament , do you have any idea when would you be able to accept the PR and update the nuget packages?

**Comment by AdamDiament** [comment]
Next week when I am back from holiday

**Comment by AmrYousef** [comment]
Awesome and welcome back 👌✌
